### ISSUE TITLE
Add mod stats to log

### ISSUE THREAD

**Issue by ddiestler** [GottFaust/WWDC#1]
[Post](http://boards.4chan.org/vg/thread/101227542#p101262540)

> while we're on the subject, gott can you include a quick listing of all the mods/ranks in the summary log output for the next release? maybe have that and the weapon name right above the enemy TTKs so we have a quick copypastable block of text or something, like I've seen you post in the past

**Comment by GottFaust** [comment]
Handled in 0.6.9
