### ISSUE TITLE
Direct output comparison

### ISSUE THREAD

**Issue by Frupus** [GottFaust/WWDC#4]
Feature request: Checkbox next to Calculate that changes the output form from generating an entirely new output to a direct comparison between the previous and current values.
New numbers would appear right of the previous numbers with a <, > or = sign between the numbers or numbers would be color coded (red, green, white).
Only works for the same target group.

**Comment by GottFaust** [comment]
Work coming in 0.7.4 shortly.  Went with a second graph in a tabbed setup with the old DPS graph for ease of viewing.
