### ISSUE TITLE
oxium osprey/bursa armor values

### ISSUE THREAD

**Issue by simon-pabst** [GottFaust/WWDC#6]
Hey, doesn't look like i can add a PR, but I noticed some incorrect armor types/values in etc/Constants.java, this is what they should be according to the wiki:

"Oxium Osprey,1,95,40,750,150,Robotic,FerriteArmor,Shields,Corpus,2",
"Bursa,1,95,200,1200,700,Robotic,AlloyArmor,Shields,Corpus,2",

Especially the Bursa Ferrite Armor skews the results when optimising against Corpus enemies.

Great project, looking forward to your next release!

**Comment by spmuladoo** [comment]
Hey thanks! Most enemy strings were put together years ago and I never gave a proper look at them. I'll update these.

**Comment by simon-pabst** [comment]
Great, I'll let you know if I find more little things like this.
