### ISSUE TITLE
Could not access mods.dbCould

### ISSUE THREAD

**Issue by Kheopsian** [GottFaust/WWDC#7]
Hello, your program look really promising, i was looking for a software like this for a long time and you did a great job on calculation. However I encounter a problem while running it. It says i can't access a db, which result in not having any weapon or mod on the list if I don't create mine. I read a bit of your code but was unable to see whrere the db connection is created so, i just sent an issue. Have a good day ;)

**Comment by spmuladoo** [comment]
The default db are coded into the program itself (though mostly out-of-date), then it creates db files in its folder. There may be permissions preventing the program from creating the db files.
